// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkBPcpdjF-HXoOrC6gvuLFpVbcjDA5qJo',
    appId: '1:359677695752:web:885941e763908d79fdfebd',
    messagingSenderId: '359677695752',
    projectId: 'frontier-dives',
    authDomain: 'frontier-dives.firebaseapp.com',
    databaseURL: 'https://frontier-dives-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'frontier-dives.firebasestorage.app',
    measurementId: 'G-MLY0E7BWS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI1A3Bl0cw11MEcANdsGifW5bVY3K1Wm0',
    appId: '1:359677695752:android:67aa6b7ebce8e893fdfebd',
    messagingSenderId: '359677695752',
    projectId: 'frontier-dives',
    databaseURL: 'https://frontier-dives-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'frontier-dives.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8-Hvy8TwnGWxZqcIslS3Ue4eQSAV6weI',
    appId: '1:359677695752:ios:3b766e3ac77f98c3fdfebd',
    messagingSenderId: '359677695752',
    projectId: 'frontier-dives',
    databaseURL: 'https://frontier-dives-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'frontier-dives.firebasestorage.app',
    iosBundleId: 'com.example.frontierdives',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8-Hvy8TwnGWxZqcIslS3Ue4eQSAV6weI',
    appId: '1:359677695752:ios:3b766e3ac77f98c3fdfebd',
    messagingSenderId: '359677695752',
    projectId: 'frontier-dives',
    databaseURL: 'https://frontier-dives-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'frontier-dives.firebasestorage.app',
    iosBundleId: 'com.example.frontierdives',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkBPcpdjF-HXoOrC6gvuLFpVbcjDA5qJo',
    appId: '1:359677695752:web:7b65606f3d17e383fdfebd',
    messagingSenderId: '359677695752',
    projectId: 'frontier-dives',
    authDomain: 'frontier-dives.firebaseapp.com',
    databaseURL: 'https://frontier-dives-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'frontier-dives.firebasestorage.app',
    measurementId: 'G-1K6K2DC472',
  );
}
